CREATE TABLE "GCG_6815_SHIP_EXPORT" (
 "TRANS_DATE" CHAR(8),
 "TRANS_TIME" CHAR(8),
 "SCANNED_BY" CHAR(30),
 "JOB" CHAR(15),
 "CO_NUM" CHAR(7) NOT NULL,
 "CUST_PO" CHAR(35),
 "CUST_PO_LINE" CHAR(4) NOT NULL,
 "QTY_SHIPPED" NUMERIC(13,4) NOT NULL,
 "STAT" CHAR(7), 
 "ERR_CODE" BIT,
 "TRANS_NUM" CHAR(7)); 